#!/usr/bin/env python3
"""
Setup script for the FTC Teams Fetcher

This script helps set up the environment for fetching FTC teams data.
It will create a .env file with the necessary configuration.
"""

import os
import sys
import getpass
from pathlib import Path


def create_env_file():
    """Create a .env file with FTC API credentials"""
    env_file = Path('.env')
    
    print("🔧 FTC Teams Fetcher Setup")
    print("=" * 40)
    print()
    
    if env_file.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").lower().strip()
        if response != 'y':
            print("Setup cancelled.")
            return False
    
    print("Please enter your FTC API credentials:")
    print("(You can get these from https://ftc-events.firstinspires.org/services/API)")
    print()
    
    username = input("FTC API Username: ").strip()
    if not username:
        print("❌ Username is required!")
        return False
    
    api_key = getpass.getpass("FTC API Key: ").strip()
    if not api_key:
        print("❌ API Key is required!")
        return False
    
    print()
    print("Please enter your AWS credentials:")
    print("(You can get these from AWS IAM Console -> Users -> Security credentials)")
    print("Note: These are needed for the script to access AWS services like DynamoDB")
    print()
    
    aws_access_key = getpass.getpass("AWS Access Key ID: ").strip()
    if not aws_access_key:
        print("❌ AWS Access Key ID is required!")
        return False
    
    aws_secret_key = getpass.getpass("AWS Secret Access Key: ").strip()
    if not aws_secret_key:
        print("❌ AWS Secret Access Key is required!")
        return False
    
    aws_region = input("AWS Region (default: us-east-1): ").strip()
    if not aws_region:
        aws_region = "us-east-1"
    
    # Create .env content
    env_content = f"""# FTC Teams Fetcher Configuration
# Generated by setup_teams_fetcher.py

# FTC API Credentials
FTC_API_USERNAME={username}
FTC_API_KEY={api_key}

# AWS Credentials
AWS_ACCESS_KEY_ID={aws_access_key}
AWS_SECRET_ACCESS_KEY={aws_secret_key}
AWS_DEFAULT_REGION={aws_region}

# Optional: Logging configuration
LOG_LEVEL=INFO
"""
    
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        
        print(f"✅ Created {env_file}")
        print()
        print("🚀 Setup complete! You can now run:")
        print("   python fetch_teams_by_season.py 2024")
        print()
        print("📝 Note: Make sure to keep your .env file secure and don't commit it to version control.")
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False


def check_dependencies():
    """Check if required dependencies are available"""
    print("🔍 Checking dependencies...")
    
    required_modules = ['aiohttp', 'asyncio']
    missing_modules = []
    
    for module in required_modules:
        try:
            __import__(module)
            print(f"  ✅ {module}")
        except ImportError:
            print(f"  ❌ {module}")
            missing_modules.append(module)
    
    if missing_modules:
        print()
        print("⚠️  Missing dependencies detected!")
        print("Please install them with:")
        print(f"   pip install {' '.join(missing_modules)}")
        return False
    
    print("✅ All dependencies are available!")
    return True


def main():
    """Main setup function"""
    print("Welcome to the FTC Teams Fetcher setup!")
    print()
    
    # Check dependencies first
    if not check_dependencies():
        print()
        print("Please install missing dependencies and run setup again.")
        sys.exit(1)
    
    print()
    
    # Create .env file
    if create_env_file():
        print()
        print("🎉 Setup completed successfully!")
        print()
        print("Usage examples:")
        print("  python fetch_teams_by_season.py 2024")
        print("  python fetch_teams_by_season.py 2023 --verbose")
        print("  python fetch_teams_by_season.py 2024 --output-dir ./data")
    else:
        print("❌ Setup failed!")
        sys.exit(1)


if __name__ == "__main__":
    main()
